name: QuicktestPRAgainstDev

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]


jobs:

  test:
    name: Run quicktest on PR branch
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: fetch repos
        run: |
          ./fetch-repos.sh

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile.finn
          context: .
          push: false
          load: true
          tags: finn_gha
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


      - name: DockerRunQuicktest
        run: |
          docker run --init --hostname finn_gha -w $(pwd) -v $(pwd):$(pwd) -e FINN_ROOT=$(pwd) -e FINN_BUILD_DIR=/tmp/finn_gha -e FINN_INST_NAME=finn_gha finn_gha quicktest.sh
