name: QuicktestPRAgainstDev

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]


jobs:

  test:
    name: Run quicktest on PR branch
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: DockerRunQuicktest
        run: |
          docker build -t finn_gha -f docker/Dockerfile.finn .
          docker run --init --hostname finn_gha -v $(pwd):/workspace/finn -e FINN_BUILD_DIR=/tmp/finn_gha -e FINN_INST_NAME=finn_gha finn_gha quicktest.sh
